require: rubocop-rails

inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false
  
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

AllCops:
  Exclude:
    - 'client/node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/*'
  NewCops: enable 